#!/usr/xpg4/bin/sh

. /lib/svc/share/smf_include.sh

# Set a reasonable ulimit
ulimit -n 65535

# Allow more than 256 file descriptors on Solaris 10 32bit
# See the following URL for a full description:
# http://developers.sun.com/solaris/articles/stdio_256.html
export LD_PRELOAD_32=/usr/lib/extendedFILE.so.1

PATHPREFIX=/opt/local

getprop() {
    PROPVAL=""
    svcprop -q -p $1 ${SMF_FMRI}
    if [ $? -eq 0 ] ; then
        PROPVAL=`svcprop -p $1 ${SMF_FMRI}`
        if [ "${PROPVAL}" = "\"\"" ] ; then
            PROPVAL=""
        fi  
        return
    fi  
    return
}

POWERDNS_BIN=${PATHPREFIX}/sbin

getprop powerdns/startup_options
if [ "${PROPVAL}" != "" ] ; then
        echo startupoptions set
        echo val=${PROPVAL}
        STARTUP_OPTIONS="${PROPVAL} "
fi

getprop powerdns/config_dir
if [ "${PROPVAL}" != "" ] ; then
  STARTUP_OPTIONS="--config-dir=${PROPVAL} ${STARTUP_OPTIONS}"
fi

case "$1" in
  start)
    echo "Starting PowerDNS: \c"
    ${POWERDNS_BIN}/pdns_server ${STARTUP_OPTIONS}
    echo "powerdns."
    ;;
  *)
    echo "Usage: $0 {start}"
    exit 1
    ;;
esac

exit 0
